on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/checks-run@v4.21.1
        with:
          Verbose: True
          
