on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
    - uses: actions/checkout@v3
    - uses: liquibase-github-actions/update@v4.21.1
      with:
        changelogFile: "changelog.oracle.sql"
        url: ${{ secrets.URL }}
        password: ${{ secrets.PASSWORD }}
        username: ${{ secrets.USERNAME }}

